version: '3'

services:
  wmb:
    image: gitea.findlayis.me/chuck/sms-ircd:latest
    environment: 
        - SERVER_NAME=sms-ircd
        - SERVER_PORT=6555
    ports:
        - "6555:6555"
    restart: always